Added safety check to alarm boot setter
Prevents crash if app was never opened or was cleared since last open.
(prevents java.lang.RuntimeException: Unable to start receiver
com.kuxhausen.huemore.timing.BootSetter:
android.database.sqlite.SQLiteException: no such table:)